// File generated by FlutterFire CLI.
// generated after flutterfire configure command
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPNPnlbmccBJ1rQd360vffQDjutcKESU',
    appId: '1:745038350243:android:09542efa66821f03d87c16',
    messagingSenderId: '745038350243',
    projectId: 'chat-app-84150',
    storageBucket: 'chat-app-84150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASb2LG7eFKP_5FSY-uGzUeTTnC0932g4s',
    appId: '1:745038350243:ios:a90b740712cf31a6d87c16',
    messagingSenderId: '745038350243',
    projectId: 'chat-app-84150',
    storageBucket: 'chat-app-84150.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAsAaHtQjzYid7GK-ArK5ewnargjL0DQ',
    appId: '1:745038350243:web:815dd813c0ce19d7d87c16',
    messagingSenderId: '745038350243',
    projectId: 'chat-app-84150',
    authDomain: 'chat-app-84150.firebaseapp.com',
    storageBucket: 'chat-app-84150.appspot.com',
  );

}